// <auto-generated/>
using ComponentHub.ApiClients.Api.Auth;
using ComponentHub.ApiClients.Api.Components;
using ComponentHub.ApiClients.Api.Testing;
using ComponentHub.ApiClients.Api.Users;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace ComponentHub.ApiClients.Api {
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    public class ApiRequestBuilder : BaseRequestBuilder {
        /// <summary>The auth property</summary>
        public AuthRequestBuilder Auth { get =>
            new AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The components property</summary>
        public ComponentsRequestBuilder Components { get =>
            new ComponentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The testing property</summary>
        public TestingRequestBuilder Testing { get =>
            new TestingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public UsersRequestBuilder Users { get =>
            new UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new ApiRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new ApiRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl) {
        }
    }
}
