// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace ComponentHub.ApiClients.Models {
    public class GetComponentResponse : IParsable {
        /// <summary>The componentEntry property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ComponentEntryDto? ComponentEntry { get; set; }
#nullable restore
#else
        public ComponentEntryDto ComponentEntry { get; set; }
#endif
        /// <summary>The currentComponent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ComponentDto? CurrentComponent { get; set; }
#nullable restore
#else
        public ComponentDto CurrentComponent { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static GetComponentResponse CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new GetComponentResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"componentEntry", n => { ComponentEntry = n.GetObjectValue<ComponentEntryDto>(ComponentEntryDto.CreateFromDiscriminatorValue); } },
                {"currentComponent", n => { CurrentComponent = n.GetObjectValue<ComponentDto>(ComponentDto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<ComponentEntryDto>("componentEntry", ComponentEntry);
            writer.WriteObjectValue<ComponentDto>("currentComponent", CurrentComponent);
        }
    }
}
