// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ComponentHub.ApiClients.Models {
    public enum Language {
        [EnumMember(Value = "JS")]
        JS,
        [EnumMember(Value = "TS")]
        TS,
    }
}
