// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace ComponentHub.ApiClients.Models {
    public class SearchUsers_ResponseDto : IParsable {
        /// <summary>The pagination property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ResponsePagination? Pagination { get; set; }
#nullable restore
#else
        public ResponsePagination Pagination { get; set; }
#endif
        /// <summary>The publicUserInfos property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<PublicUserDto>? PublicUserInfos { get; set; }
#nullable restore
#else
        public List<PublicUserDto> PublicUserInfos { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static SearchUsers_ResponseDto CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new SearchUsers_ResponseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"pagination", n => { Pagination = n.GetObjectValue<ResponsePagination>(ResponsePagination.CreateFromDiscriminatorValue); } },
                {"publicUserInfos", n => { PublicUserInfos = n.GetCollectionOfObjectValues<PublicUserDto>(PublicUserDto.CreateFromDiscriminatorValue)?.ToList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<ResponsePagination>("pagination", Pagination);
            writer.WriteCollectionOfObjectValues<PublicUserDto>("publicUserInfos", PublicUserInfos);
        }
    }
}
