// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ComponentHub.ApiClients.Models {
    public enum SortingMethod {
        [EnumMember(Value = "ByUserName")]
        ByUserName,
        [EnumMember(Value = "ByName")]
        ByName,
        [EnumMember(Value = "ByCreationDate")]
        ByCreationDate,
        [EnumMember(Value = "ByUpdateDate")]
        ByUpdateDate,
    }
}
