// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ComponentHub.ApiClients.Models {
    public enum SortDirection {
        [EnumMember(Value = "Ascending")]
        Ascending,
        [EnumMember(Value = "Descending")]
        Descending,
    }
}
