// <auto-generated/>
using ComponentHub.ApiClients.Api.Users.ChangeName;
using ComponentHub.ApiClients.Api.Users.Delete;
using ComponentHub.ApiClients.Api.Users.DetailedInfo;
using ComponentHub.ApiClients.Api.Users.Download;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace ComponentHub.ApiClients.Api.Users {
    /// <summary>
    /// Builds and executes requests for operations under \api\users
    /// </summary>
    public class UsersRequestBuilder : BaseRequestBuilder {
        /// <summary>The changeName property</summary>
        public ChangeNameRequestBuilder ChangeName { get =>
            new ChangeNameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deletePath property</summary>
        public DeleteRequestBuilder DeletePath { get =>
            new DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The detailedInfo property</summary>
        public DetailedInfoRequestBuilder DetailedInfo { get =>
            new DetailedInfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The download property</summary>
        public DownloadRequestBuilder Download { get =>
            new DownloadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new UsersRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/users", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new UsersRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/users", rawUrl) {
        }
    }
}
