// <auto-generated/>
using ComponentHub.ApiClients.Api.Components.Get.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace ComponentHub.ApiClients.Api.Components.Get {
    /// <summary>
    /// Builds and executes requests for operations under \api\components\get
    /// </summary>
    public class GetRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the ComponentHub.ApiClients.api.components.get.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        public WithUserNameItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("userName", position);
            return new WithUserNameItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new GetRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/components/get", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new GetRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/components/get", rawUrl) {
        }
    }
}
